// <auto-generated />
using System;
using AjudaLaServices.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AjudaLaServices.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("AjudaLaServices.Api.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContratanteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datahora")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrestadorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContratanteId");

                    b.HasIndex("PrestadorId");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("AjudaLaServices.Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("AjudaLaServices.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPerfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AjudaLaServices.Api.Models.Agendamento", b =>
                {
                    b.HasOne("AjudaLaServices.Api.Models.Usuario", "Contratante")
                        .WithMany("ServicosContratados")
                        .HasForeignKey("ContratanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AjudaLaServices.Api.Models.Usuario", "Prestador")
                        .WithMany("ServicosPrestados")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contratante");

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("AjudaLaServices.Api.Models.Usuario", b =>
                {
                    b.HasOne("AjudaLaServices.Api.Models.Categoria", "Categoria")
                        .WithMany("Prestadores")
                        .HasForeignKey("CategoriaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("AjudaLaServices.Api.Models.Categoria", b =>
                {
                    b.Navigation("Prestadores");
                });

            modelBuilder.Entity("AjudaLaServices.Api.Models.Usuario", b =>
                {
                    b.Navigation("ServicosContratados");

                    b.Navigation("ServicosPrestados");
                });
#pragma warning restore 612, 618
        }
    }
}
